---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appservice
  namespace: bazaar
  labels:
    app: mainapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      annotations:
        getambassador.io/inject-traffic-agent: enabled
      labels:
        app: mainapp
    spec:
      containers:
        - name: appservice
          image: docker.io/brucehorn/ambassador_service_preview_demo-appservice:latest  
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
