apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageservice
  labels:
    app: imageapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageapp
  template:
    metadata:
      annotations:
        getambassador.io/inject-traffic-agent: enabled
      labels:
        app: imageapp
    spec:
      containers:
        - name: imageservice
          image: brucehorn/service_preview-imageservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: imageservice
spec:
  selector:
    app: imageapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: imageservice
  namespace: default
spec:
  prefix: /image/
  service: imageservice

