apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageservice
  labels:
    app: imageapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageapp
  template:
    metadata:
      annotations:
        getambassador.io/inject-traffic-agent: enabled
      labels:
        app: imageapp
    spec:
      containers:
        - name: imageservice
          image: docker.io/brucehorn/ambassador_service_preview_demo-imageservice
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: imageservice
spec:
  selector:
    app: imageapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: imageservice
  namespace: default
spec:
  prefix: /image/
  service: imageservice

