apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyservice
  labels:
    app: pyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyservice
        image: brucehorn/service_preview-pyservice:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pyservice
spec:
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: pyservice
  namespace: default
spec:
  prefix: /py/
  service: pyservice
