---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: inventoryservice
  namespace: bazaar
spec:
  host: aes-demo.mturner.k736.net
  prefix: /inventory/
  service: inventoryservice.bazaar:80
---
