apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
  labels:
    app: inventoryapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryapp
  template:
    metadata:
      annotations:
        getambassador.io/inject-traffic-agent: enabled
      labels:
        app: inventoryapp
    spec:
      containers:
        - name: inventoryservice
          image: docker.io/brucehorn/service_preview-inventoryservice:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
spec:
  selector:
    app: inventoryapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: inventoryservice
  namespace: default
spec:
  prefix: /inventory/
  service: inventoryservice
