---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: imageservice
  namespace: bazaar
  labels:
    public-api: "false"    ## labels for matching only some Mappings
    documented: "false"    ## (note that "true" must be quoted)
spec:
  host: aes-demo.com
  prefix: /image/
  service: imageservice.bazaar:80
  docs: 
    url: https://api.swaggerhub.com/apis/matt-aes/appservice/1.0.0/swagger.json
---
