apiVersion: apps/v1
kind: Deployment
metadata:
  name: appservice
  labels:
    app: appservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      containers:
        - name: appservice
          image: brucehorn/service_preview-appservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: mainapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: an-app-service
  namespace: default
spec:
  prefix: /app/
  service: appservice

