apiVersion: apps/v1
kind: Deployment
metadata:
  name: goservice
  labels:
    app: goservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: goservice
          image: brucehorn/service_preview-goservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: goservice
spec:
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: a-go-service
  namespace: default
spec:
  prefix: /go/
  service: goservice

